<a href="https://colab.research.google.com/github/aditiR2508/Creating-and-Loading-Datasets/blob/main/Expt10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 10
## Creating and Loading Datasets
## Aditi Rathore
## 25070123006
## EnTC A1

In [2]:
#dataframe to csv
import pandas as pd

data = {
    "Roll_no": [1, 2, 3, 4, 5],
    "Gender": ["female", "female", "male", "male", "female"],
    "Department": ["EnTC", "AIML", "CSE", "EnTC", "MECH"],
    "CGPA": [9.0, 7.2, 8.8, 8.5, 7.9]
}

df = pd.DataFrame(data)

df.to_csv("student_data.csv", index=False)

In [3]:
#shape of dataframe
df.shape

(5, 4)

In [4]:
#dataframe to excel
import pandas as pd

data = {
    "Roll_no": [1, 2, 3, 4, 5],
    "Gender": ["female", "female", "male", "male", "female"],
    "Department": ["EnTC", "AIML", "CSE", "EnTC", "MECH"],
    "CGPA": [9.0, 7.2, 8.8, 8.5, 7.9]
}

df = pd.DataFrame(data)

df.to_excel("student_data.xlsx", index=False)

In [5]:
#accessing information of a specific column
df["Department"]

0    EnTC
1    AIML
2     CSE
3    EnTC
4    MECH
Name: Department, dtype: object

In [6]:
# Accessing information of roll no. 3

roll_no_3 = df[df["Roll_no"] == 3]
print(roll_no_3)

   Roll_no Gender Department  CGPA
2        3   male        CSE   8.8

In [7]:
# To find data types of each column

df.dtypes

Roll_no         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [8]:
# Performing mean,median and mode operation on provided data

print("Mean:", df["CGPA"].mean())
print("Median:", df["CGPA"].median())
print("Mode:", df["CGPA"].mode()[0])

Mean: 8.28
Median: 8.5
Mode: 7.2

In [9]:
# Inserting a new column

df["Grade"] = ["A", "C+", "B+", "B+", "B"]

print(df)

   Roll_no  Gender Department  CGPA Grade
0        1  female       EnTC   9.0     A
1        2  female       AIML   7.2    C+
2        3    male        CSE   8.8    B+
3        4    male       EnTC   8.5    B+
4        5  female       MECH   7.9     B

In [10]:
# Deleting a column

df = df.drop("Gender", axis=1)

print(df)

   Roll_no Department  CGPA Grade
0        1       EnTC   9.0     A
1        2       AIML   7.2    C+
2        3        CSE   8.8    B+
3        4       EnTC   8.5    B+
4        5       MECH   7.9     B

In [12]:
#CGPA of topper
topper_cgpa = df.loc[df["CGPA"].idxmax(), "CGPA"]
df

   Roll_no Department  CGPA Grade
0        1       EnTC   9.0     A
1        2       AIML   7.2    C+
2        3        CSE   8.8    B+
3        4       EnTC   8.5    B+
4        5       MECH   7.9     B

In [13]:
#CGPA of roll no 2
roll_no_2_cgpa = df.loc[df["Roll_no"] == 2, "CGPA"].values
df

   Roll_no Department  CGPA Grade
0        1       EnTC   9.0     A
1        2       AIML   7.2    C+
2        3        CSE   8.8    B+
3        4       EnTC   8.5    B+
4        5       MECH   7.9     B

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [22]:
df.head()

   Roll_no Department  CGPA Grade
0        1       EnTC   9.0     A
1        2       AIML   7.2    C+
2        3        CSE   8.8    B+
3        4       EnTC   8.5    B+
4        5       MECH   7.9     B

In [23]:
df.tail()

   Roll_no Department  CGPA Grade
0        1       EnTC   9.0     A
1        2       AIML   7.2    C+
2        3        CSE   8.8    B+
3        4       EnTC   8.5    B+
4        5       MECH   7.9     B